{% set name = "unlikely" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python {{ python }}
  host:
    - pip
    - python {{ python }}
  run:
    - dask
    - matplotlib
    - numpy
    - pandas
    - python
    - scipy
    - tqdm

about:
  home: "https://github.com/edderic/unlikely"
  license: MIT
  license_family: MIT
  summary: "Parallelized, Likelihood-free Bayesian Inference"
  dev_url: "https://github.com/edderic/unlikely"

extra:
  recipe-maintainers:
    - edderic
test:
  imports:
    - unlikely
    - unlikely.explorations
    - unlikely.misc
    - unlikely.models
    - unlikely.priors

